# Crowdin Configuration File
# https://developer.crowdin.com/configuration-file/

project_id: '677271'
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .

files:
  - source: /locales/en.json
    translation: /locales/%locale%.json
    languages_mapping:
      locale:
        zh-TW: zh-TW
        vi: vi

  - source: /changelogs/en.json
    translation: /changelogs/%locale%.json
    languages_mapping:
      locale:
        zh-TW: zh-TW
        vi: vi
